language: ruby
script: bundle exec middleman build
env:
  global:
  - GIT_COMMITTER_NAME=Yuichiro Someya
  - GIT_COMMITTER_EMAIL=ayemos.y@gmail.com
  - GIT_AUTHOR_NAME=Yuichiro Someya
  - GIT_AUTHOR_EMAIL=ayemos.y@gmail.com
  - secure: SFhtZh6YxwfMRsQ7+4FvGFEBGT52fVhTOk1UZT33sG2yPkpCAEBYMHuZg+SB+n2zr6zu2C1lvrtE1c18t1UP59H3BsjYvwkso8PV7JOVwqQtWLhBg2felxY/WgU6QEVW4D2fpjnmj8hgOVKuzlvKd6r317PO8Y3N71lwvH9l84TMaz6zf2ldI4LETUsZXhZpeNh6W3+hDyDglUXxaZMdCFJIFrOs/QRbmg90nL22kM0yRwq3AnoqyrYLIACnAfYabgjkehUvnR7mWd4/w8GTjkGM70dp2QODHHyFCOQEy7Q+Aa5qKMs3neJngD43O9bkp3teJqGB/Jl9GOCG4Evt3CiRYsq7KIgkcjNXAgaLexARs9akQ+b2BKnhcxp/3EW6yZpacSRT4WGHDzdQ6oHsB05MECUEZ/OB9RANspiOQ8PedlMxELPsNuQW/AtyeCENrAYBke7u4waJ1TGaQuczQ0wtDKcTPLYng/AlO0iFhPmp7TGMi0PR2Jl9XgNlzHcE+RBsJ/3D65zht19nzl6TleBOf6FGy2XU7U3OOiXZoD/AkG4g56VH9QbW1htwFJDayUNP/gNv6jPr/OWyFXCSZT06HLMkumIAidvtjAVg9I9LS16V2P2QYx/tVJBucNCA3APst8atgDrkDjTmx+3JS/zEEu/K/lx4h9tXBn932pY=
before_script:
  - git clone --quiet https://github.com/ayemos/neeah.git build
  - pushd build
  - git checkout -b gh-pages
  - popd
after_success:
  - cd build
  - git add -A
  - git commit -m 'Update'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/ayemos/neeah.git
    gh-pages'
